SELECT * FROM securityRole where RECID = '886285'

SELECT * FROM securityUserRole where /*USER_ = 'Vladisla' and*/ SECURITYROLE = '735411'--'Ivan.Bat'

SELECT * FROM OMUserRoleOrganization where USER_ = 'Vladisla'--'Ivan.Bat'

/*
INSERT INTO OMUserRoleOrganization (OMINTERNALORGANIZATION,OMHIERARCHYTYPE,SECURITYROLEASSIGNMENTRULE,USER_,SECURITYROLE)
VALUES (5637180921,0,0,'Vladisla',886356)
*/

SELECT * FROM SECURITYUSERROLE AS sur
RIGHT JOIN OMUSERROLEORGANIZATION AS omu ON omu.SECURITYROLE = sur.SECURITYROLE
WHERE sur.USER_ = 'Vladisla'


SELECT DATAAREA,NAME FROM COMPANYINFOVIEW AS civ
INNER JOIN OMUSERROLEORGANIZATION AS omu ON omu.OMINTERNALORGANIZATION = civ.RECID
WHERE omu.USER_ = 'Vladisla'

--DELETE FROM OMUSERROLEORGANIZATION WHERE OMINTERNALORGANIZATION =  5637180921

SELECT * FROM OMUSERROLEORGANIZATION WHERE USER_ ='Vladisla' --and OMINTERNALORGANIZATION =  5637180921

SELECT * FROM COMPANYINFOVIEW

select * 
  from SQLDICTIONARY
where FIELDID <> 0 and NAME = 'CUSTTABLE'--and TABLEID = 504

SELECT * FROM CUSTTABLE

/*
select * from securityRole
INNER JOIN securityUserRole AS s ON s.
where securityRole.RecId == securityUserRole.SecurityRole;
*/