SELECT * FROM PURCHLINE
SELECT * FROM PURCHTABLE
SELECT * FROM PURCHTABLE WHERE ORDERACCOUNT LIKE 'VE0153%'


SELECT PURCHLINE.PURCHID,PURCHLINE.Name,PURCHLINE.ITEMID,PURCHLINE.PURCHQTY,PURCHLINE.DELIVERYDATE,
PURCHTABLE.ConsigneeAccount_HV,PURCHTABLE.CREATEDDATETIME
FROM PURCHLINE
INNER JOIN PURCHTABLE ON PURCHLINE.PURCHID = PURCHTABLE.PURCHID
WHERE PURCHTABLE.ConsigneeAccount_HV = '01531'