SELECT
PURCHLINE.PURCHID,
PURCHLINE.Name,
PURCHLINE.ITEMID,
PURCHLINE.PURCHQTY,
PURCHLINE.DELIVERYDATE,
PURCHTABLE.ConsigneeAccount_HV,
PURCHTABLE.CREATEDDATETIME,
PURCHLINE.PURCHSTATUS
,(case when PURCHLINE.PURCHSTATUS = 3 then VENDINVOICETRANS.INVOICEDATE
             else NULL
             end) as INVOICEDATE
FROM PURCHLINE
INNER JOIN PURCHTABLE ON PURCHLINE.PURCHID = PURCHTABLE.PURCHID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID AND PURCHLINE.PARTITION = PURCHTABLE.PARTITION
LEFT JOIN VENDINVOICETRANS ON VENDINVOICETRANS.ORIGPURCHID = PURCHLINE.PURCHID and vendinvoicetrans.INVENTTRANSID = purchline.INVENTTRANSID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID AND PURCHLINE.PARTITION = PURCHTABLE.PARTITION
WHERE
PURCHTABLE.ConsigneeAccount_HV = '01531'
AND PURCHLINE.PURCHQTY > 0
AND PURCHLINE.QTYORDERED <> 0