SELECT
PURCHLINE.PURCHID,
PURCHLINE.Name,
PURCHLINE.ITEMID,
PURCHLINE.PURCHQTY,
PURCHLINE.DELIVERYDATE,
PURCHLINE.QtyKGA_HV,
PURCHTABLE.ConsigneeAccount_HV,
PURCHTABLE.CREATEDDATETIME,
SALESTABLE.DESTINATION_HV,
(CASE WHEN PURCHLINE.PURCHSTATUS = 1 THEN 'OPEN ORDER'
			ELSE 'None' END) AS PURCHSTATUS,
(CASE WHEN INVENTTABLE.PRODUCTGROUPID_HV = '' AND INVENTTABLE.CLASSIFIER_HV2_ = '' THEN ''
			ELSE (INVENTTABLE.PRODUCTGROUPID_HV + ' - ' + CLASSIFIER_HV2_) END) AS ACTIVESUBSTANCE
FROM PURCHLINE
INNER JOIN PURCHTABLE ON PURCHLINE.PURCHID = PURCHTABLE.PURCHID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID
LEFT JOIN VENDINVOICETRANS ON VENDINVOICETRANS.ORIGPURCHID = PURCHLINE.PURCHID and vendinvoicetrans.INVENTTRANSID = purchline.INVENTTRANSID 
INNER JOIN SALESTABLE ON PURCHLINE.INVENTREFID = SALESTABLE.SALESID 
RIGHT JOIN INVENTTABLE ON PURCHLINE.ITEMID = INVENTTABLE.ITEMID 
WHERE
PURCHLINE.PURCHSTATUS = 1
AND PURCHLINE.PURCHQTY > 0
AND PURCHLINE.QTYORDERED <> 0
--DATAAREA ID
AND PURCHLINE.DATAAREAID = '410'
AND PURCHTABLE.DATAAREAID = '410'
--AND VENDINVOICETRANS.DATAAREAID = '410`'		%IS NULL%
AND SALESTABLE.DATAAREAID = '410'
AND INVENTTABLE.DATAAREAID = '410'
--PARTITION
AND PURCHLINE.PARTITION = '5637144576'
AND PURCHTABLE.PARTITION = '5637144576'
--AND VENDINVOICETRANS.PARTITION = '5637144576'		%IS NULL%
AND SALESTABLE.PARTITION = '5637144576'
AND INVENTTABLE.PARTITION = '5637144576'
AND PURCHTABLE.ConsigneeAccount_HV = '01531'
GROUP BY PURCHLINE.PURCHID,
PURCHLINE.Name,
PURCHLINE.ITEMID,
PURCHLINE.PURCHQTY,
PURCHLINE.DELIVERYDATE,
PURCHLINE.QtyKGA_HV,
PURCHTABLE.ConsigneeAccount_HV,
PURCHTABLE.CREATEDDATETIME,
SALESTABLE.DESTINATION_HV,
PURCHLINE.PURCHSTATUS,
INVENTTABLE.CLASSIFIER_HV2_,
INVENTTABLE.PRODUCTGROUPID_HV

