SELECT
PURCHLINE.PURCHID,
PURCHLINE.Name,
PURCHLINE.ITEMID,
PURCHLINE.PURCHQTY,
PURCHLINE.DELIVERYDATE,
PURCHLINE.QtyKGA_HV,
PURCHTABLE.ConsigneeAccount_HV,
PURCHTABLE.CREATEDDATETIME,
SALESTABLE.DESTINATION_HV,
INVENTBATCH.CONVERTFACTORKGA_HV
,(case when PURCHLINE.PURCHSTATUS = 3 then VENDINVOICETRANS.INVOICEDATE
             else NULL
             end) as INVOICEDATE
,(CASE WHEN PURCHLINE.PURCHSTATUS = 1 THEN 'OPEN ORDER'
			WHEN PURCHLINE.PURCHSTATUS = 2 THEN 'RECEIVED'
			WHEN PURCHLINE.PURCHSTATUS = 3 THEN 'INVOICED'
			WHEN PURCHLINE.PURCHSTATUS = 4 THEN 'CANCELED'
			ELSE 'None' END) AS PURCHSTATUS
FROM PURCHLINE
INNER JOIN PURCHTABLE ON PURCHLINE.PURCHID = PURCHTABLE.PURCHID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID AND PURCHLINE.PARTITION = PURCHTABLE.PARTITION
LEFT JOIN VENDINVOICETRANS ON VENDINVOICETRANS.ORIGPURCHID = PURCHLINE.PURCHID and vendinvoicetrans.INVENTTRANSID = purchline.INVENTTRANSID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID AND PURCHLINE.PARTITION = PURCHTABLE.PARTITION
INNER JOIN SALESTABLE ON PURCHLINE.INVENTREFID = SALESTABLE.SALESID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID AND PURCHLINE.PARTITION = PURCHTABLE.PARTITION
INNER JOIN INVENTDIM ON PURCHLINE.INVENTDIMID = INVENTDIM.INVENTDIMID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID AND PURCHLINE.PARTITION = PURCHTABLE.PARTITION
INNER JOIN INVENTBATCH ON INVENTDIM.INVENTBATCHID = INVENTBATCH.INVENTBATCHID AND PURCHLINE.DATAAREAID = PURCHTABLE.DATAAREAID AND PURCHLINE.PARTITION = PURCHTABLE.PARTITION
WHERE
PURCHTABLE.ConsigneeAccount_HV = '01531'
AND PURCHLINE.PURCHQTY > 0
AND PURCHLINE.QTYORDERED <> 0
