SELECT
ctc.ACCOUNTNUM AS [Customer Number],
ctc.NAME AS [Customer Name],
ctc.DESTINATION_HV AS [Destination],
ctc.INVENTLOCATION AS [InventLocation],
dpav.ZIPCODE AS [Zip Code],
REPLACE(REPLACE( dpav.CITY,CHAR(13),''),CHAR(10),'') AS [City],
REPLACE(REPLACE( dpav.STREET,CHAR(13),''),CHAR(10),'') AS [Street Address],
dpt.NAME AS [Sales Responsible],
ct.DEL_PHONE AS [Phone number],
ctc.DATAAREAID AS [Company]
FROM CUSTTABLECUBE AS ctc
LEFT JOIN HCMWORKER AS hw on hw.RECID = ctc.SALESRESPONSIBLE_BG  
LEFT JOIN DIRPARTYTABLE AS dpt ON dpt.RECID = hw.PERSON
LEFT JOIN CUSTTABLE AS ct ON ct.ACCOUNTNUM = ctc.ACCOUNTNUM AND ctc.DATAAREAID = ct.DATAAREAID
LEFT JOIN DIRPARTYPOSTALADDRESSVIEW AS dpav ON ct.PARTY = dpav.PARTY
WHERE ctc.DATAAREAID = '110'

