/*		NOT WORK
SELECT
ct.ACCOUNTNUM AS [Customer Number],
dpt.NAME AS [Customer Name],
lpa.ZIPCODE,
lpa.CITY,
lpa.STREET AS [Street Address],
dpt.NAME AS [Sales Responsible],
--dpt.NAMEALIAS AS [Sales Responsible],
ct.DEL_PHONE AS [Phone number],
ct.DATAAREAID AS [Company]
FROM CUSTTABLE AS ct
LEFT JOIN DIRPARTYTABLE AS dpt ON dpt.RECID = ct.PARTY 
LEFT JOIN LOGISTICSPOSTALADDRESS AS lpa ON lpa.RECID = dpt.RECID
LEFT JOIN HCMWORKER hw on hw.RECID = ct.SALESRESPONSIBLE_BG
WHERE ct.DATAAREAID  = '110'
AND ct.ACCOUNTNUM = '00685'
*/

SELECT
ctc.ACCOUNTNUM AS [Customer Number],
ctc.NAME AS [Customer Name],
lpa.ZIPCODE AS [Zip Code],
lpa.CITY AS [City],
lpa.STREET AS [Street Address],
dpt.NAME AS [Sales Responsible],
ct.DEL_PHONE AS [Phone number],
ctc.DATAAREAID AS [Company]
FROM CUSTTABLECUBE AS ctc
LEFT JOIN HCMWORKER AS hw on hw.RECID = ctc.SALESRESPONSIBLE_BG  
LEFT JOIN DIRPARTYTABLE AS dpt ON dpt.RECID = hw.PERSON
LEFT JOIN LOGISTICSPOSTALADDRESS AS lpa ON lpa.RECID = dpt.RECID
LEFT JOIN CUSTTABLE AS ct ON ct.ACCOUNTNUM = ctc.ACCOUNTNUM AND ctc.DATAAREAID = ct.DATAAREAID
WHERE ctc.DATAAREAID = '110'
--AND ctc.ACCOUNTNUM = '00685'

