USE [GrassioTraining]
GO

/****** Object:  View [dbo].[Z_PURCHCUBEHVP]    Script Date: 6/6/2018 10:32:35 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[Z_PURCHCUBEHVP] AS 
SELECT T1.RECID AS PL_RECID,
T1.PURCHREQID AS PL_PURCHREQID,
T1.PURCHID AS PL_PURCHID,
T1.LINENUMBER AS PL_LINENUMBER,
T1.DELIVERYDATE AS PL_DELIVERYDATE,
T1.LINEAMOUNT AS PL_LINEAMOUNT,
T1.INVENTTRANSID AS PL_INVENTTRANSID,
T1.DATAAREAID AS DATAAREAID,
T1.PARTITION AS PARTITION,
T1.RECID AS RECID,
T2.DATAAREAID AS DATAAREAID#2,
T2.PARTITION AS PARTITION#2,
T2.ORDERACCOUNT AS PT_ORDERACCOUNT,
T2.PURCHNAME AS PT_PURCHNAME,
T3.PARTITION AS PARTITION#3,
T4.PARTITION AS PARTITION#4,
T5.DATAAREAID AS DATAAREAID#5,
T5.PARTITION AS PARTITION#5,
T5.INVOICEDATE AS VT_INVOICEDATE,
T5.CURRENCYCODE AS VT_CURRENCYCODE,
T5.DESTCOUNTRYREGIONID AS VT_DESTCOUNTRYREGIONID,
T5.DISCAMOUNT AS VT_DISCAMOUNT,
T5.DISCPERCENT AS VT_DISCPERCENT,
T5.INVOICEID AS VT_INVOICEID,
T5.LINENUM AS VT_LINENUM,
T6.DATAAREAID AS DATAAREAID#6,
T6.PARTITION AS PARTITION#6 
FROM PURCHLINE T1 
CROSS JOIN PURCHTABLE T2 
LEFT OUTER JOIN ECORESCATEGORY T3 ON (T1.PROCUREMENTCATEGORY=T3.RECID AND (T1.PARTITION = T3.PARTITION)) 
LEFT OUTER JOIN PURCHREQLINE T4 ON ((T1.PURCHREQLINEREFID=T4.LINEREFID AND (T1.PARTITION = T4.PARTITION)) AND (T1.PURCHID=T4.PURCHID AND (T1.PARTITION = T4.PARTITION)))
 LEFT OUTER JOIN VENDINVOICETRANS T5 ON (T1.INVENTTRANSID=T5.INVENTTRANSID AND (T1.DATAAREAID = T5.DATAAREAID) AND (T1.PARTITION = T5.PARTITION))
  LEFT OUTER JOIN CC_ITEMS_TEST T6 ON (T1.ITEMID=T6.ITEMID AND (T1.DATAAREAID = T6.DATAAREAID) AND (T1.PARTITION = T6.PARTITION))
   WHERE (((T1.PURCHID=T2.PURCHID 
   AND (T1.DATAAREAID = T2.DATAAREAID) 
   AND (T1.PARTITION = T2.PARTITION)) 
   AND (T1.DATAAREAID=T2.DATAAREAID 
   AND (T1.DATAAREAID = T2.DATAAREAID) 
   AND (T1.PARTITION = T2.PARTITION))) 
   AND (T1.PARTITION=T2.PARTITION 
   AND (T1.DATAAREAID = T2.DATAAREAID)))
GO


